### PR TITLE
Fixed python lib problem

### PR DESCRIPTION
**Pull request by pichuang**
Upgrade netaddr, six, pbr

```
netaddr 0.7.10 -> 0.7.14
six     1.5.2  -> 1.9.0
pbr     x      -> 1.1.1
```

### CODE REVIEW

**Comment by fujita** [comment]
Why newer versions of these packages are necessary?

**Comment by pichuang** [comment]
Sorry for the late reply.
I try to use your dockerfile, I found three library (netaddr, six, pbr) need be upgrade.
So I use pip to upgrade these libs.

About netaddr

**Comment by fujita** [comment]
Ah, thanks!

The latest version of Ryu needs the newer version of eventlet too. I fixed Dockerfile:
- use 15.04 for newer eventlet (eventlet is implemented in C so pip is useless).
- install all the pure python libraries via pip for letting pip handle dependency.

Please try the latest image at dockerhub. Thanks!

**Comment by pichuang** [comment]
:+1:

**Pull request closed without merging**
